[default]
SQLALCHEMY_DATABASE_URI="" # Setting this to avoid warnings
DB_USER="postgres"
DB_PASSWORD=""
DB_HOST="db"
DB_NAME="human_factor"
SQLALCHEMY_TRACK_MODIFICATIONS="False"
VIDEO_BUCKET="dev.videos.thehumanfactor.ai"
JWT_SECRET_KEY="fake-secret"
JWT_BLACKLIST_ENABLED="True"
JWT_BLACKLIST_TOKEN_CHECKS="refresh"
PROPAGATE_EXCEPTIONS="True"
ALLOWED_ORIGINS="*"
GIT_COMMIT_SHA="local"

[development]
DB_HOST="db"

[testing]
GIT_COMMIT_SHA="{{GIT_COMMIT_SHA}}"
SENTRY_DSN="https://e58d119f6182413798cd669a8a46ddc9@sentry.io/1494502"

[staging]
DB_HOST="human-api-db-postgresql.staging.svc.cluster.local"
VIDEO_BUCKET="staging.videos.thehumanfactor.ai"
GIT_COMMIT_SHA="{{GIT_COMMIT_SHA}}"
SENTRY_DSN="https://e58d119f6182413798cd669a8a46ddc9@sentry.io/1494502"

[production]
VIDEO_BUCKET="prod.videos.thehumanfactor.ai"
GIT_COMMIT_SHA="{{GIT_COMMIT_SHA}}"
SENTRY_DSN="https://e58d119f6182413798cd669a8a46ddc9@sentry.io/1494502"
