[default]
SQLALCHEMY_DATABASE_URI="" # Setting this to avoid warnings
DB_USER="postgres"
DB_PASSWORD=""
DB_HOST="db"
DB_NAME="human_factor"
SQLALCHEMY_TRACK_MODIFICATIONS="False"
VIDEO_BUCKET="dev.videos.thehumanfactor.ai"
JWT_SECRET_KEY="fake-secret"
JWT_BLACKLIST_ENABLED="True"
JWT_BLACKLIST_TOKEN_CHECKS="refresh"
PROPAGATE_EXCEPTIONS="True"
ALLOWED_ORIGINS="*"
SENTRY_RELEASE_ID="local"

[development]
DB_HOST="db"

[testing]
SENTRY_RELEASE_ID="{{RELEASE_ID}}"

[staging]
DB_HOST="human-api-db-postgresql.staging.svc.cluster.local"
VIDEO_BUCKET="staging.videos.thehumanfactor.ai"
SENTRY_RELEASE_ID="{{RELEASE_ID}}"

[production]
VIDEO_BUCKET="prod.videos.thehumanfactor.ai"
SENTRY_RELEASE_ID="{{RELEASE_ID}}"
