version: 2.1

executors:
  gcp:
    docker:
      - image: google/cloud-sdk



jobs:
  build:
    working_directory: ~/repo
    executor: gcp
    steps:
      - checkout
      - run:
          name: Install Docker Compose
          command: |
            curl -L https://github.com/docker/compose/releases/download/1.23.2/docker-compose-`uname -s`-`uname -m` > ~/docker-compose
            chmod +x ~/docker-compose
            mv ~/docker-compose /usr/local/bin/docker-compose
      - setup_remote_docker:
         docker_layer_caching: true

      - run:
          name: Start container and verify it is working
          command: |
            set -x
            docker-compose -f docker-compose.circle.yaml up -d
            docker-compose exec api pipenv run flask db upgrade
            docker-compose exec api pipenv run pytest
      - run:
          name: Auth with GCP
          command: |
            echo $GCLOUD_SERVICE_KEY | gcloud auth activate-service-account --key-file=-
            gcloud config set project $GOOGLE_PROJECT_ID
            gcloud config set compute/zone $GOOGLE_COMPUTE_ZONE
            echo $GCLOUD_SERVICE_KEY | docker login -u _json_key --password-stdin https://gcr.io

      - run:
          name: Build tag and push Docker image
          command: |
            docker build --target prod-env -t gcr.io/the-human-factor/human-api:${CIRCLE_SHA1} .
            if [ $(git rev-parse --abbrev-ref HEAD)==master ]; then docker tag gcr.io/the-human-factor/human-api:${CIRCLE_SHA1} gcr.io/the-human-factor/human-api:latest; fi
            docker push gcr.io/the-human-factor/human-api

  deploy-dev:
    executor: gcp
    steps:
      - run:
          name: Auth with GCP
          command: |
            echo $GCLOUD_SERVICE_KEY | gcloud auth activate-service-account --key-file=-
            gcloud config set project $GOOGLE_PROJECT_ID
            gcloud config set compute/zone $GOOGLE_COMPUTE_ZONE
            gcloud container clusters get-credentials main-1

      - run:
          name: Deploy to dev namespace
          command: |
            kubectl config set-context --current --namespace=development
            kubectl set image deployment human-api-deployment human-api=gcr.io/the-human-factor/human-api:${CIRCLE_SHA1} --record

workflows:
  version: 2
  build:
    jobs:
      - build
      - deploy-dev:
          filters:
            branches:
              only:
                - master
          requires:
            - build
