version: 2.1

executors:
  gcp:
    docker:
      - image: google/cloud-sdk

jobs:
  build:
    working_directory: ~/repo
    executor: gcp
    steps:
      - checkout
      - run:
          name: Install Docker Compose
          command: |
            curl -L https://github.com/docker/compose/releases/download/1.23.2/docker-compose-`uname -s`-`uname -m` > ~/docker-compose
            chmod +x ~/docker-compose
            mv ~/docker-compose /usr/local/bin/docker-compose
      - setup_remote_docker:
         docker_layer_caching: true

      - run:
          name: Start container and verify it is working
          command: |
            set -x
            docker-compose build --parallel
            docker-compose -f docker-compose.circle.yaml up -d
            docker-compose exec api pipenv run flask db upgrade
            docker-compose exec api bash -c "FLASK_ENV=testing ENV_FOR_DYNACONF=testing pipenv run pytest"

      - run:
          name: Auth with GCP
          command: |
            echo $GCLOUD_SERVICE_KEY | gcloud auth activate-service-account --key-file=-
            gcloud config set project $GOOGLE_PROJECT_ID
            gcloud config set compute/zone $GOOGLE_COMPUTE_ZONE
            echo $GCLOUD_SERVICE_KEY | docker login -u _json_key --password-stdin https://gcr.io

      - run:
          name: Build, tag and push Docker image
          command: |
            sed -i "s/{{GIT_COMMIT_SHA}}/$(git rev-parse HEAD)/g" settings.toml
            docker build --target prod-env -t gcr.io/the-human-factor/human-api:${CIRCLE_SHA1} .
            docker tag gcr.io/the-human-factor/human-api:${CIRCLE_SHA1} gcr.io/the-human-factor/human-api:$(git rev-parse --abbrev-ref HEAD | sed 's/\//__/g')
            docker push gcr.io/the-human-factor/human-api

  deploy-staging:
    executor: gcp
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: Install Sentry CLI
          command: |
            curl -sL https://deb.nodesource.com/setup_12.x | bash -
            apt-get install -y nodejs
            npm install @sentry/cli

      - run:
          name: Create Sentry release
          command: |
            export VERSION=$(./node_modules/.bin/sentry-cli releases propose-version)

            # Create a release
            ./node_modules/.bin/sentry-cli releases new -p human-factor-api $VERSION

      - run:
          name: Auth with GCP
          command: |
            echo $GCLOUD_SERVICE_KEY | gcloud auth activate-service-account --key-file=-
            gcloud config set project $GOOGLE_PROJECT_ID
            gcloud config set compute/zone $GOOGLE_COMPUTE_ZONE
            gcloud container clusters get-credentials main-1

      - run:
          name: Deploy to staging namespace
          command: |
            kubectl config set-context --current --namespace=staging
            kubectl set image deployment staging-human-api-deployment human-api=gcr.io/the-human-factor/human-api:${CIRCLE_SHA1} --record
      - run:
          name: Finalize Sentry release
          command: |
            export VERSION=$(./node_modules/.bin/sentry-cli releases propose-version)

            # Associate commits with the release
            ./node_modules/.bin/sentry-cli releases set-commits --auto $VERSION

            # Finalize release
            ./node_modules/.bin/sentry-cli releases finalize $VERSION

workflows:
  version: 2
  build:
    jobs:
      - build
      - deploy-staging:
          filters:
            branches:
              only:
                - master
          requires:
            - build
