apiVersion: v1
kind: Service
metadata:
  name: human-api-service
spec:
  selector:
    app: human-api
    color: blue
  ports:
    - port: 9000
      protocol: TCP
  type: LoadBalancer
  loadBalancerIP: "35.239.14.192" # human-api-service-dev-ip accessible via VPC network in GCP
