"""expand video for reencoded url, video stats and images

Revision ID: 11ddcccec497
Revises: 934c08136a7c
Create Date: 2019-09-06 21:56:32.304131

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects.postgresql import UUID

# revision identifiers, used by Alembic.
revision = '11ddcccec497'
down_revision = '934c08136a7c'
branch_labels = None
depends_on = None

videos_helper = sa.Table(
  'videos',
  sa.MetaData(),
  sa.Column('id', UUID(as_uuid=True), primary_key=True),
  sa.Column('url', db.String(512)),
  sa.Column('source_url', db.String(512))
)


def upgrade():
  connection = op.get_bind()

  # ### commands auto generated by Alembic - please adjust! ###
  op.add_column('videos', sa.Column('source_duration_sec', sa.Float(), nullable=True))
  op.add_column('videos', sa.Column('source_height', sa.Integer(), nullable=True))
  op.add_column('videos', sa.Column('source_url', sa.String(length=512), nullable=True))
  op.add_column('videos', sa.Column('source_width', sa.Integer(), nullable=True))
  op.add_column('videos', sa.Column('still_url', sa.String(length=512), nullable=True))
  op.add_column('videos', sa.Column('thumbnail_url', sa.String(length=512), nullable=True))
  # ### end Alembic commands ###

  # Copy urls over
  for video in connection.execute(videos_helper.select()):
    connection.execute(
      videos_helper.update().where(
        videos_helper.c.id == video.id
      ).values(
        source_url=url
      )
    )


def downgrade():
  # ### commands auto generated by Alembic - please adjust! ###
  op.drop_column('videos', 'thumbnail_url')
  op.drop_column('videos', 'still_url')
  op.drop_column('videos', 'source_width')
  op.drop_column('videos', 'source_url')
  op.drop_column('videos', 'source_height')
  op.drop_column('videos', 'source_duration_sec')
  # ### end Alembic commands ###
