"""Add deleted_at to challenges

Revision ID: 27b8286ec905
Revises: bc8f9416732d
Create Date: 2019-10-05 05:13:12.076599

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "27b8286ec905"
down_revision = "bc8f9416732d"
branch_labels = None
depends_on = None


def upgrade():
  # ### commands auto generated by Alembic - please adjust! ###
  op.add_column(
    "challenges", sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True)
  )
  # ### end Alembic commands ###


def downgrade():
  # ### commands auto generated by Alembic - please adjust! ###
  op.drop_column("challenges", "deleted_at")
  # ### end Alembic commands ###
