"""Adds listed flag for challenges

Revision ID: 923d61108bd6
Revises: 94e8139261e4
Create Date: 2019-09-22 08:37:02.959833

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "923d61108bd6"
down_revision = "94e8139261e4"
branch_labels = None
depends_on = None


def upgrade():
  # ### commands auto generated by Alembic - please adjust! ###
  op.add_column(
    "challenges", sa.Column("listed", sa.Boolean(), server_default="f", nullable=False)
  )
  op.create_index("challenges_by_user_id_listed", "challenges", ["user_id", "listed"])
  # ### end Alembic commands ###


def downgrade():
  # ### commands auto generated by Alembic - please adjust! ###
  op.drop_column("challenges", "listed")
  # ### end Alembic commands ###
