"""Adds index on listed challenges

Revision ID: bc8f9416732d
Revises: 923d61108bd6
Create Date: 2019-09-22 10:04:50.743872

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bc8f9416732d'
down_revision = '923d61108bd6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_challenges_listed'), 'challenges', ['listed'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_challenges_listed'), table_name='challenges')
    # ### end Alembic commands ###
