"""Adds encoded_at timestamp

Revision ID: e62d063f87e7
Revises: 11ddcccec497
Create Date: 2019-09-13 00:46:42.945184

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e62d063f87e7'
down_revision = '11ddcccec497'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('videos', sa.Column('encoded_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('videos', 'encoded_at')
    # ### end Alembic commands ###
